name: CI
on:
  pull_request:
  push:
    branches-ignore:
    - dependabot/*
    - renovate/*
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up system
      run: bin/before_install
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
      timeout-minutes: 30
    - name: Run tests
      run: bundle exec rake
    - name: Deploy
      if: "${{ github.event_name == 'push' && github.repository_owner == 'ManageIQ' && github.ref_name == 'master' }}"
      run: bin/deploy
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
